-- This migration script enriches the 'companies' table with a 'tags' column
-- to store an array of tags generated by NLP or keyword analysis.

ALTER TABLE public.companies
ADD COLUMN IF NOT EXISTS tags text[];

COMMENT ON COLUMN public.companies.tags IS 'An array of tags (e.g., "fintech", "work-life balance") generated from analysis of company data.';

-- Notify PostgREST to reload its schema cache
NOTIFY pgrst, 'reload schema';
