name: Deploy API to Cloud Run
on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - "shared/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.server.ts"
      - "Dockerfile"
      - ".github/workflows/cloud-run.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # REQUIRED for WIF
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: deploy@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push
        run: |
          gcloud builds submit --tag ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/containers/je-api .

      - name: Deploy
        run: |
          gcloud run deploy je-api \
            --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/containers/je-api \
            --region ${{ vars.GCP_REGION }} \
            --service-account je-api-runner@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-secrets "SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest"

      - name: Show URL
        run: gcloud run services describe je-api --region ${{ vars.GCP_REGION }} --format='value(status.url)'
