name: GCP Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build with Cloud Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: jobequal
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: github-actions@jobequal.iam.gserviceaccount.com
          token_format: access_token
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit ./server \
            --tag europe-west6-docker.pkg.dev/jobequal/containers/je-api:latest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: jobequal
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: github-actions@jobequal.iam.gserviceaccount.com
          token_format: access_token
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy je-api \
            --image=europe-west6-docker.pkg.dev/jobequal/containers/je-api:latest \
            --region=europe-west6 \
            --platform=managed \
            --allow-unauthenticated
