name: WIF Smoke Test
on: { workflow_dispatch: {} }
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v5
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: deploy@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          gcloud config get-value project
          gcloud auth list
          gcloud run services list --region ${{ vars.GCP_REGION }} --format='table(name,url)'
